version: "3"

services:

  mongo:
    image: mongo:4.2-bionic
    restart: unless-stopped
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: friends
    volumes:
    - ./docker/mongo_users.js:/docker-entrypoint-initdb.d/001_users.js:ro

  mongo-express:
    image: mongo-express:0.54
    restart: unless-stopped
    depends_on:
    - mongo
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_BASICAUTH_USERNAME: web
      ME_CONFIG_BASICAUTH_PASSWORD: 123

  node:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
    - 8080:8080
    depends_on:
    - mongo
    environment:
      MONGODB_HOST: mongo
    volumes:
    - ./src:/usr/src/app/src
