version: "3"

services:
  mongo:
    image: mongo:4.2-bionic
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: friends
    volumes:
      - ./mongo_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
